### ISSUE TITLE
Crash when css is not properly formed

### ISSUE THREAD

**Issue by PuKoren** [Automattic/juice#106]
Crash log when juicing bad syntaxed css:

```sh
Error: Unexpected } (line 2860, char 23512)
    at parseError (/home/koren/dev/corp/corp-screen/node_modules/dom-extractor/node_modules/juice/node_modules/cssom/lib/parse.js:54:15)
    at Object.parse (/home/koren/dev/corp/corp-screen/node_modules/dom-extractor/node_modules/juice/node_modules/cssom/lib/parse.js:325:7)
    at Object.exports.parseCSS (/home/koren/dev/corp/corp-screen/node_modules/dom-extractor/node_modules/juice/lib/utils.js:58:21)
    at inlineDocument (/home/koren/dev/corp/corp-screen/node_modules/dom-extractor/node_modules/juice/lib/juice.js:65:21)
    at Function.juiceDocument (/home/koren/dev/corp/corp-screen/node_modules/dom-extractor/node_modules/juice/lib/juice.js:171:3)
    at cssCallback (/home/koren/dev/corp/corp-screen/node_modules/dom-extractor/src/dom-extractor.js:53:17)
    at inlineCss (/home/koren/dev/corp/corp-screen/node_modules/dom-extractor/src/dom-extractor.js:73:3)
    at Request._callback (/home/koren/dev/corp/corp-screen/node_modules/dom-extractor/src/dom-extractor.js:80:4)
    at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickDomainCallback (node.js:463:13)

```

**Comment by PuKoren** [comment]
Had to try/catch juice

**Comment by Andersos** [comment]
Could you provide the code that produced the error?

**Comment by PuKoren** [comment]
Sure, I tried to inline a html file with a link: 
```html
<link rel="stylesheet" href="http://s.camif.fr/skin/frontend/enterprise/camif/css/main.css"/>
```
Error is when parsing its content with cssom, I can reproduce it with cssom only using:
```js
cssom.parse(CSS_CONTENT);
```

**Comment by Andersos** [comment]
Did you use [webResources](https://github.com/Automattic/juice/blob/master/README.md#options)?

**Comment by PuKoren** [comment]
I used juice.juiceResources with no parameter, should I add css files into webResources and it will work ? Should it be fetched automaticaly with webResources ?

**Comment by Andersos** [comment]
You need to send it in as part of the options parameter.

**Comment by parshap** [comment]
@Andersos: I don't think this issue is related to the resource inliner - it's that cssom will throw an error any malformed css.

**Comment by PuKoren** [comment]
Exact, and the whole inlining will be canceled if any of the fetched css file contains an error

**Comment by parshap** [comment]
@PuKoren: What would you expect to happen? Browsers are pretty good and will parse "as much" of the CSS as possible. Unfortunately I don't think any of the node css parsers are that resilient.

I guess at worst we could print a warning and skip that file, but continue with the rest.

**Comment by PuKoren** [comment]
@parshap  It would be nice to continue the job if parsing fails on one file
I did some testing and it appears that cssom returns successfully parsed nodes in the errors so he also does "as much as possible" but this error is not handled by the css fetcher

**Comment by parshap** [comment]
@PuKoren Nice! Sounds like we can achieve similar behavior to browsers then. I would reopen the issue. I also encourage you to submit a PR for this if you're up for the task. I think the change would be pretty straight forward and contained in the [`util.parseCSS` function](https://github.com/Automattic/juice/blob/5d97143e7fbb51795c6eae18803f590b7ef4e410/lib/utils.js#L57-L73).

**Comment by jrit** [comment]
If we start bypassing this error, which seems reasonable, I think we should `console.warm()` that there was a failure to process some specific part of the content. That will make fixing the underlying problems with the document/CSS much easier for users and avoid an issue where users think some of their CSS isn't inlined because juice is broken.

**Comment by YuHuaiChen** [comment]
Sorry for interrupting, I'm getting the
```
path_to_project/node_modules/juice/node_modules/cssom/lib/parse.js:58
		throw error;
		      ^
Error: Unexpected } (line 15, char 255)
at parseError (path_to_project/node_modules/juice/node_modules/cssom/lib/parse.js:54:15)
```
error, too.

I don't know how to make juice to bypass the error and just keep on doing without exiting.
So...is this feature already there but haven't been documented yet, or is there any work around?

Thanks for any help!!
