### ISSUE TITLE
ReferenceError in strict mode on iojs

### ISSUE THREAD

**Issue by tsabolov** [Automattic/juice#133]
I'm using [`node-email-templates`](https://github.com/niftylettuce/node-email-templates) library for generating emails. Recently I've switched to `iojs` to get new ES2015 features. In order to be able to use ES2015 classes iojs must be run in strict mode (with `--use_strict` parameter). But when I try to render a template it crashes with the error:

```
ReferenceError: doc is not defined
    at juice (/Users/tsabolov/dev/node-boilerplate/node_modules/email-templates/node_modules/juice/lib/juice.js:10:7)
    at /Users/tsabolov/dev/node-boilerplate/node_modules/email-templates/lib/email-template.js:134:39
    at tryCatcher (/Users/tsabolov/dev/node-boilerplate/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/tsabolov/dev/node-boilerplate/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/tsabolov/dev/node-boilerplate/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/Users/tsabolov/dev/node-boilerplate/node_modules/bluebird/js/main/async.js:187:12)
    at Async._drainQueues (/Users/tsabolov/dev/node-boilerplate/node_modules/bluebird/js/main/async.js:192:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/tsabolov/dev/node-boilerplate/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

As you can see the error is caused by the using of undeclared variable `doc` in `juice.js`. I guess it's a mistake and `doc` must be declared with `var`.

**Comment by jrit** [comment]
Thanks. We should definitely declare and enforce everything as `"use strict"`. It might also be useful to start specifying iojs as a target on Travis, though I think that might still run without optional flags... I'm not a Travis expert.

**Comment by jrit** [comment]
Master should be use_strict compliant now. @tsabolov do you have an opportunity to test against your environment before a release is published?

**Comment by tsabolov** [comment]
@jrit I've installed the package using `npm i Automattic/juice` and everything works like a charm. Thanks a lot for super fast fix.
