### ISSUE TITLE
CLI --options-file [filepath] loads from pwd not full path provided

### ISSUE THREAD

**Issue by centrex** [Automattic/juice#200]
If you provide a filepath to the options file, the current directory is prepended to the file path.

Example:

cd /somedir
juice --options-file /path/to/options/juice_options.json input.html output.html 2>&1

module.js:340
    throw err;
          ^
Error: Cannot find module '/somedir/path/to/options/juice_options.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib64/node_modules/juice/bin/juice:19:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by jrit** [comment]
Yeah, I can see how you'd expect otherwise. I'll update it to check if it is absolute and handle appropriately.
