### ISSUE TITLE
Selector issue crashes process instead of returning error

### ISSUE THREAD

**Issue by JonasGruenwald** [Automattic/juice#350]
Hi, I'm using this very useful package to inline styles of websites I'm scraping with node, but I keep encountering this error every now and then:

```
/Users/jonas/Projects/personal/web-element-grabber-full/node_modules/juice/lib/inline.js:302
  if (selector.length === 0) {
               ^

TypeError: Cannot read property 'length' of undefined
    at getPseudoElementType (/Users/jonas/Projects/personal/web-element-grabber-full/node_modules/juice/lib/inline.js:302:16)
    at handleRule (/Users/jonas/Projects/personal/web-element-grabber-full/node_modules/juice/lib/inline.js:82:29)
    at Array.forEach (<anonymous>)
    at inlineDocument (/Users/jonas/Projects/personal/web-element-grabber-full/node_modules/juice/lib/inline.js:34:9)
    at juiceDocument (/Users/jonas/Projects/personal/web-element-grabber-full/node_modules/juice/lib/inline.js:332:3)
    at module.exports (/Users/jonas/Projects/personal/web-element-grabber-full/node_modules/juice/lib/cheerio.js:61:22)
    at onInline (/Users/jonas/Projects/personal/web-element-grabber-full/node_modules/juice/index.js:75:7)
    at /Users/jonas/Projects/personal/web-element-grabber-full/node_modules/web-resource-inliner/src/html.js:267:9
    at /Users/jonas/Projects/personal/web-element-grabber-full/node_modules/async/dist/async.js:2955:19
    at wrapper (/Users/jonas/Projects/personal/web-element-grabber-full/node_modules/async/dist/async.js:268:20)
```

In principle that's not a problem, I assume the website being scraped has some malformed html, and I expect this to happen, however since this error is not caught and the process quits instead of the callback from juiceResources returning an error I can't properly handle the error.
I've tried additionally wrapping the call to juiceResources in a try/catch, but it did not catch the error.

Is there a way to have this error not quit the node process?

**Comment by jrit** [comment]
I believe #349 fixed this
