### ISSUE TITLE
Using Juice on the client-side

### ISSUE THREAD

**Issue by samholmes** [Automattic/juice#38]
This is the error I get when I try to use `juice.inlineContent(html, css)`:

    /Users/holmes/Code/foobar/app/node_modules/browserify/lib/wrap.js:445
                throw moduleError('Cannot find module');
                      ^
    Error: Cannot find module: "canvas" from directory "/Users/holmes/Code/foobar/app/node_modules/juice/node_modules/jsdom/lib/jsdom/level2" while processing file /Users/holmes/Code/foobar/app/node_modules/juice/node_modules/jsdom/lib/jsdom/level2/html.js
        at moduleError (/Users/holmes/Code/foobar/app/node_modules/browserify/lib/wrap.js:406:16)
        at Wrap.require (/Users/holmes/Code/foobar/app/node_modules/browserify/lib/wrap.js:445:19)
        at Wrap.require (/Users/holmes/Code/foobar/app/node_modules/browserify/lib/wrap.js:537:14)
        at Array.forEach (native)
        at Wrap.require (/Users/holmes/Code/foobar/app/node_modules/browserify/lib/wrap.js:519:27)
        at Wrap.require (/Users/holmes/Code/foobar/app/node_modules/browserify/lib/wrap.js:537:14)
        at Array.forEach (native)
        at Wrap.require (/Users/holmes/Code/foobar/app/node_modules/browserify/lib/wrap.js:519:27)
        at Wrap.require (/Users/holmes/Code/foobar/app/node_modules/browserify/lib/wrap.js:537:14)
        at Array.forEach (native)

I'm using Juice client-side via browserify 1.15.

Can Juice work on the client-side? I don't see why it couldn't.

**Comment by edouard-lopez** [comment]
Any progress on this?

**Comment by jrit** [comment]
jsdom was removed for 1.x, which was a major blocker since it was a native module, but I'm not sure off hand what other blockers there are to in-browser use. Probably the most useful thing at this stage would be to assess what problems currently exist so we can make a roadmap to fixing them.

**Comment by oncletom** [comment]
Even if there are some remaining node/native modules, they can be replaced at browserification time.

**Comment by edouard-lopez** [comment]
My quick attempts failed miserably with obscure errors (it was my first use of `browserify`).
We have reconsider approach so the front-end packaging won't be necessary for us.

**Comment by barretts** [comment]
My co-worker and I had some luck the other day by removing web-resource-inliner and fs dependancies. I know this isn't feasible for everyone but it worked well in webpack, V8 and Chrome. I made a basic example in a fork of what we did https://github.com/barretts/juice
