### ISSUE TITLE
Crash when requiring

### ISSUE THREAD

**Issue by juliomarcos** [Automattic/juice#78]
It's crashing since the last csstyle update (I suppose)

Error: Cannot find module './properties'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Julio\Desktop\visitavirtual-api\node_modules
\juice\node_modules\jsdom\node_modules\cssstyle\lib\CSSStyleDeclaration.js:209:1
)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Andersos** [comment]
This can probably be closed or are you still experiencing this problem @juliomarcos ?

**Comment by juliomarcos** [comment]
I can't remember, sorry. I will close the issue.
